// Generated by CoffeeScript 1.3.3
(function() {

  describe("Eggs environment", function() {
    return it("should have Eggs", function() {
      return expect(Eggs).not.toBe(null);
    });
  });

}).call(this);
