// Generated by CoffeeScript 1.3.3
(function() {
  var Eggs, Model, escapeRegExp, namedParam, optionalParam, routeStripper, splatParam;

  Eggs = this.Eggs = {};

  Eggs.Model = Model = (function() {

    function Model(attributes, options) {
      var attributeNamesBus, attributeNamesProperty, attrs, attrsInitialValidationError, defaults, setAttributesBus, validAttributesBus, validAttributesProperty, validSingleAttributes,
        _this = this;
      options = _.defaults({}, options, {
        shouldValidate: true
      });
      attrs = attributes || {};
      if (defaults = _.result(this, 'defaults')) {
        attrs = _.defaults({}, attrs, defaults);
      }
      attrsInitialValidationError = options.shouldValidate && (typeof this.validate === "function" ? this.validate(_.clone(attrs)) : void 0);
      validAttributesBus = new Bacon.Bus;
      if (!attrsInitialValidationError) {
        validAttributesProperty = validAttributesBus.toProperty(_.clone(attrs));
      } else {
        validAttributesProperty = validAttributesBus.toProperty();
      }
      validSingleAttributes = {};
      setAttributesBus = new Bacon.Bus;
      attributeNamesBus = new Bacon.Bus;
      if (!attrsInitialValidationError) {
        attributeNamesProperty = attributeNamesBus.toProperty(_.keys(attrs));
      } else {
        attributeNamesProperty = attributeNamesBus.toProperty();
      }
      setAttributesBus.map(function(value) {
        return _.defaults({}, value, attrs);
      }).onValue(function(attrObject) {
        var error;
        if (_.isEqual(attrObject, attrs)) {
          return;
        }
        if (options.shouldValidate && (error = typeof _this.validate === "function" ? _this.validate(attrObject) : void 0)) {
          return validAttributesBus.error({
            error: error,
            attributes: attrObject
          });
        } else {
          attrsInitialValidationError = null;
          if (_.difference(_.keys(attrObject), _.keys(attrs)).length) {
            attributeNamesBus.push(_.keys(attrObject));
          }
          return validAttributesBus.push(_.clone(attrs = attrObject));
        }
      });
      this.attributes = function(name, value) {
        var newAttrs, setObject;
        if (arguments.length === 0) {
          return validAttributesProperty;
        }
        if (arguments.length === 1) {
          if (_.isObject(name)) {
            return setAttributesBus.push(name);
          } else if (_.has(attrs, name)) {
            if (!validAttributesProperty[name]) {
              if (!attrsInitialValidationError) {
                validAttributesProperty[name] = validAttributesBus.map("." + name).toProperty(attrs[name]);
              } else {
                validAttributesProperty[name] = validAttributesBus.map("." + name).toProperty();
              }
            }
            return validAttributesProperty[name];
          } else {
            throw "Invalid attributes accessor: " + name;
          }
        } else {
          if (_.isArray(name)) {
            if (value['unset']) {
              newAttrs = _.omit(attrs, name);
              if (_.difference(_.keys(attrs), _.keys(newAttrs))) {
                attrs = newAttrs;
                attributeNamesBus.push(_.keys(attrs));
                return validAttributesBus.push(_.clone(attrs));
              }
            }
          } else if (_.has(attrs, name)) {
            setObject = {};
            setObject[name] = value;
            return setAttributesBus.push(setObject);
          } else {
            throw "Invalid attributes update: " + name + ", " + value;
          }
        }
      };
      this.attributeNames = function() {
        return attributeNamesProperty;
      };
      this.initialize.apply(this, arguments);
    }

    Model.prototype.initialize = function() {};

    return Model;

  })();

  Eggs.model = function(extension) {
    var Surrogate, child, parent;
    parent = Model;
    if (extension && _.has(extension, 'constructor')) {
      child = extension.constructor;
    } else {
      child = function() {
        return parent.apply(this, arguments);
      };
    }
    Surrogate = (function() {

      function Surrogate() {
        this.constructor = child;
      }

      return Surrogate;

    })();
    Surrogate.prototype = parent.prototype;
    child.prototype = new Surrogate;
    if (extension) {
      _.extend(child.prototype, extension);
    }
    child.__super__ = parent.prototype;
    return child;
  };

  routeStripper = /^[#\/]|\s+$/g;

  Eggs.currentLocation = (function() {
    var getFragment, getHash, hasHashChange, hasPushState, location, windowLocationStream, _ref;
    location = typeof window !== "undefined" && window !== null ? window.location : void 0;
    hasPushState = location != null ? (_ref = location.history) != null ? _ref.pushState : void 0 : void 0;
    hasHashChange = 'onhashchange' in window;
    getHash = function() {
      var match;
      match = location.href.match(/#(.*)$/);
      if (match) {
        return match[1];
      } else {
        return '';
      }
    };
    getFragment = function(fragment) {
      if (!fragment) {
        if (hasPushState || !hasHashChange) {
          fragment = location.pathname;
        } else {
          fragment = getHash();
        }
      }
      return fragment.replace(routeStripper, '');
    };
    if (hasPushState) {
      windowLocationStream = Bacon.fromEventTarget(window, 'popstate');
    } else if (hasHashChange) {
      windowLocationStream = Bacon.fromEventTarget(window, 'hashchange');
    } else {
      windowLocationStream = Bacon.interval(100);
    }
    return windowLocationStream.map(function() {
      return getFragment();
    }).skipDuplicates().toProperty(getFragment());
  })();

  optionalParam = /\((.*?)\)/g;

  namedParam = /(\(\?)?:\w+/g;

  splatParam = /\*\w+/g;

  escapeRegExp = /[\-{}\[\]+?.,\\\^$|#\s]/g;

  Eggs.route = function(route) {
    if (!_.isRegExp(route)) {
      route = route.replace(escapeRegExp, '\\$&').replace(optionalParam, '(?:$1)?').replace(namedParam, function(match, optional) {
        if (optional) {
          return match;
        } else {
          return '([^\/]+)';
        }
      }).replace(splatParam, '(.*?)');
      route = new RegExp('^' + route + '$');
    }
    return Eggs.currentLocation.filter(function(location) {
      return route.test(location);
    }).map(function(location) {
      return route.exec(location).slice(1);
    });
  };

}).call(this);
